name: Full example tests

on:
  workflow_dispatch:

jobs:
  all-examples:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python tests/run_all_examples.py
